<?php
$sdgs = [
    [
        "title" => "1: No Poverty",
        "image" => "/img/1-goal-resources.webp",
        "image2" => "/img/subsdg1.jpg",
        "sub" => "Het Beëindigen van Extreme Armoede",
        "info" => "SDG 1 heeft als doel het beëindigen van extreme armoede over de hele wereld. Dit doel streeft naar het verminderen van het aantal mensen dat in extreme armoede leeft, met de nadruk op toegang tot basisbehoeften zoals voedsel, onderdak en gezondheidszorg. Armoede is een complex probleem dat diep ingrijpt in het leven van mensen, en SDG 1 benadrukt de noodzaak om een inclusieve en duurzame economische groei te bevorderen om armoede te bestrijden.",
        "sub2" => "Armoede in Landelijke Gebieden",
        "info2" => "Een belangrijk aspect van SDG 1 is het aanpakken van armoede in landelijke gebieden. Wereldwijd leven veel mensen in afgelegen gemeenschappen en hebben beperkte toegang tot essentiële diensten en middelen. SDG 1 benadrukt het belang van het verminderen van de armoede in deze landelijke gebieden en het waarborgen van gelijke kansen voor iedereen, ongeacht waar ze wonen. Door het aanpakken van landelijke armoede kunnen we streven naar een rechtvaardigere en welvarende toekomst voor alle mensen.",
    ],
    [
        "title" => "2: No Hunger",
        "image" => "/img/sdg2.webp",
        "image2" => "/img/subsdg2.jpg",
        "sub" => "Het Einde van Honger Wereldwijd",
        "info" => "SDG 2 streeft naar het beëindigen van honger wereldwijd. Dit doel erkent dat ondanks de vooruitgang in de afgelopen decennia, er nog steeds miljoenen mensen zijn die dagelijks met honger worden geconfronteerd. Het doel is om voedselzekerheid en voeding te bevorderen door duurzame landbouwpraktijken en verbeterde toegang tot voedsel. SDG 2 benadrukt het belang van samenwerking op wereldschaal om ervoor te zorgen dat niemand meer met honger naar bed hoeft te gaan.",
        "subtitle2" => "Duurzame Voedselsystemen",
        "info2" => "Een cruciaal aspect van SDG 2 is de ontwikkeling van duurzame voedselsystemen. Dit doel benadrukt het belang van ecologisch verantwoorde landbouwpraktijken en het verminderen van voedselverspilling. Door duurzame voedselsystemen te bevorderen, kunnen we niet alleen honger bestrijden, maar ook de gezondheid van de planeet beschermen. SDG 2 moedigt aan tot samenwerking tussen overheden, boeren, en gemeenschappen om een wereld te creëren waarin iedereen voldoende voedsel heeft en de planeet wordt behouden voor toekomstige generaties.",
    ],
    [
        "title" => "3: Good Health",
        "image" => "/img/sdg3.webp",
        "image2" => "/img/subsdg3.jpg",
        "sub" => "Toegang tot Gezondheidszorg voor Iedereen",
        "info" => "SDG 3 streeft naar goede gezondheid en welzijn voor iedereen. Het doel is om de toegang tot kwaliteitsvolle gezondheidszorg te verbeteren en gezondheidsproblemen wereldwijd aan te pakken. Dit omvat het verminderen van kindersterfte, het voorkomen van ziekten, en het bevorderen van mentale gezondheid. SDG 3 benadrukt dat gezondheid een fundamenteel mensenrecht is, en het doel is om ervoor te zorgen dat niemand wordt uitgesloten van de voordelen van goede gezondheid en welzijn.",
        "subtitle2" => "De Strijd tegen Infectieziekten",
        "info2" => "Een belangrijk aspect van SDG 3 is de strijd tegen infectieziekten. Het doel benadrukt de noodzaak om epidemieën en ziekte-uitbraken aan te pakken, zoals HIV/AIDS, malaria, tuberculose en nieuwe opkomende ziekten. SDG 3 moedigt internationale samenwerking aan om de verspreiding van infectieziekten te voorkomen en de behandeling en zorg te verbeteren. Door de strijd tegen infectieziekten aan te gaan, kunnen we de gezondheid van miljoenen mensen verbeteren en levens redden.",
    ],
    [
        "title" => "4: Quality Education",
        "image" => "/img/sdg4.webp",
        "image2" => "/img/subsdg4.jpg",
        "sub" => "Toegang tot Kwaliteitsonderwijs voor Iedereen",
        "info" => "SDG 4 streeft naar kwaliteitsonderwijs voor iedereen, ongeacht hun achtergrond. Het doel is om gelijke toegang tot onderwijs te bevorderen en de kwaliteit van het leren te verbeteren. Dit omvat basisonderwijs, voortgezet onderwijs en beroepsopleidingen. SDG 4 benadrukt het belang van onderwijs als een krachtig instrument voor persoonlijke ontwikkeling en het opbouwen van sterke, inclusieve gemeenschappen.",
        "subtitle2" => "Onderwijs voor Duurzame Ontwikkeling",
        "info2" => "Een essentieel aspect van SDG 4 is het bevorderen van onderwijs voor duurzame ontwikkeling. Dit doel benadrukt het belang van onderwijs om bewustwording te creëren over milieukwesties, sociale verantwoordelijkheid en wereldburgerschap. SDG 4 moedigt scholen en onderwijsinstellingen aan om bij te dragen aan een duurzamere toekomst door studenten te inspireren om actieve wereldburgers te worden en bij te dragen aan een rechtvaardiger wereld.",
    ],
    [
        "title" => "5: Gender Equality",
        "image" => "/img/sdg5.webp",
        "image2" => "/img/subsdg5.jpg",
        "sub" => "Bevorderen van Geslachtsgelijkheid",
        "info" => "SDG 5 richt zich op het bevorderen van geslachtsgelijkheid en het empowerment van vrouwen en meisjes. Het doel is om discriminatie en geweld tegen vrouwen en meisjes te bestrijden en ervoor te zorgen dat zij gelijke kansen hebben in alle aspecten van het leven, inclusief onderwijs, werk, en leiderschap. SDG 5 benadrukt het belang van het creëren van een rechtvaardige samenleving waarin iedereen ongeacht hun geslacht de vrijheid heeft om hun volledige potentieel te benutten.",
        "subtitle2" => "Het Belang van Vrouwelijk Leiderschap",
        "info2" => "Een belangrijk aspect van SDG 5 is het belang van vrouwelijk leiderschap. Dit doel benadrukt dat vrouwen een cruciale rol spelen in het nemen van beslissingen op alle niveaus, van de lokale gemeenschap tot de wereldwijde arena. SDG 5 moedigt aan tot de bevordering van vrouwelijk leiderschap in de politiek, het bedrijfsleven en de maatschappij als geheel. Door meer vrouwen in leiderschapsposities te brengen, kunnen we streven naar een meer inclusieve en rechtvaardige samenleving voor iedereen.",
    ],
    [
        "title" => "6: Clean Water and Sanitation",
        "image" => "/img/sdg6.webp",
        "image2" => "/img/subsdg6.jpg",
        "sub" => "Toegang tot Schoon Water voor Iedereen",
        "info" => "SDG 6 heeft als doel ervoor te zorgen dat iedereen toegang heeft tot schoon water. Het doel streeft naar het beëindigen van watergerelateerde problemen, waaronder watertekorten en verontreiniging. Schoon water is essentieel voor de gezondheid en het welzijn van mensen, en SDG 6 benadrukt het belang van het beschermen en duurzaam beheren van watervoorraden. Dit doel is gericht op het creëren van een wereld waarin iedereen veilig en betrouwbaar toegang heeft tot drinkwater en sanitaire voorzieningen.",
        "subtitle2" => "Sanitaire Voorzieningen en Hygiënebevordering",
        "info2" => "Een cruciaal aspect van SDG 6 is het bevorderen van sanitaire voorzieningen en hygiëne. Dit doel benadrukt dat verbeterde sanitaire voorzieningen en goede hygiënische praktijken essentieel zijn voor het voorkomen van ziekten en het bevorderen van een gezond leven. SDG 6 moedigt aan tot investeringen in de ontwikkeling van sanitaire voorzieningen en het verspreiden van kennis over hygiëne. Door sanitaire voorzieningen en hygiëne te bevorderen, kunnen we bijdragen aan een wereld waarin iedereen een gezonde leefomgeving heeft.",
    ],
    [
        "title" => "7: Affordable and Clean Energy",
        "image" => "/img/sdg7.webp",
        "image2" => "/img/subsdg7.jpg",
        "sub" => "Duurzame Energie voor Iedereen",
        "info" => "SDG 7 streeft naar betaalbare en duurzame energie voor iedereen. Het doel is om toegang te verschaffen tot schone en betrouwbare energiebronnen, met name in gebieden waar mensen nog steeds geen toegang hebben tot elektriciteit. SDG 7 benadrukt het belang van duurzame energiebronnen, zoals zonne- en windenergie, om de klimaatverandering tegen te gaan en de wereldwijde energiebehoefte te vervullen. Dit doel is gericht op het creëren van een wereld waarin iedereen kan profiteren van schone en betaalbare energie.",
        "subtitle2" => "Energie-efficiëntie en Klimaatactie",
        "info2" => "Een essentieel aspect van SDG 7 is het bevorderen van energie-efficiëntie en klimaatactie. Dit doel benadrukt dat we moeten streven naar een verminderd energieverbruik en een overgang naar koolstofarme energieopwekking om klimaatverandering te bestrijden. SDG 7 moedigt aan tot investeringen in energie-efficiënte technologieën en het verminderen van de CO2-uitstoot. Door energie-efficiëntie en klimaatactie te bevorderen, kunnen we bijdragen aan een duurzame toekomst voor onze planeet.",
    ],
    [
        "title" => "8: Decent Work and Economic Growth",
        "image" => "/img/sdg8.webp",
        "image2" => "/img/subsdg8.jpg",
        "sub" => "Eerlijk Werk voor Iedereen",
        "info" => "SDG 8 heeft als doel eerlijk werk en economische groei voor iedereen te bevorderen. Dit doel streeft naar het creëren van goede werkgelegenheid en fatsoenlijke arbeidsomstandigheden. Het benadrukt ook het belang van economische groei die duurzaam is en voor iedereen voordelen oplevert. SDG 8 richt zich op het bestrijden van arbeidsuitbuiting, jeugdwerkloosheid en informeel werk. Het doel is om een wereld te creëren waarin iedereen toegang heeft tot fatsoenlijk werk en een eerlijk inkomen.",
        "subtitle2" => "Ondernemerschap en Innovatie",
        "info2" => "Een belangrijk aspect van SDG 8 is het bevorderen van ondernemerschap en innovatie. Dit doel benadrukt dat het stimuleren van ondernemerschap en innovatie essentieel is voor economische groei. Het moedigt aan tot het creëren van een gunstig klimaat voor bedrijven en het ondersteunen van kleine en middelgrote ondernemingen. SDG 8 moedigt ook aan tot investeringen in onderzoek en ontwikkeling en technologische vooruitgang. Door ondernemerschap en innovatie te bevorderen, kunnen we economische groei stimuleren en banen creëren.",
    ],
    [
        "title" => "9: Industry, Innovation and Infrastructure",
        "image" => "/img/sdg9.webp",
        "image2" => "/img/subsdg9.jpg",
        "sub" => "Bevorderen van Innovatie en Industriële Groei",
        "info" => "SDG 9 heeft als doel innovatie te bevorderen en de groei van de industrie te ondersteunen. Het doel streeft naar de ontwikkeling van duurzame en veerkrachtige infrastructuur, het stimuleren van innovatie en de bevordering van inclusieve en duurzame industrialisatie. SDG 9 benadrukt het belang van investeringen in technologie en onderzoek en ontwikkeling om economische groei te stimuleren. Het doel is om een wereld te creëren waarin industrie en innovatie bijdragen aan een duurzame toekomst.",
        "subtitle2" => "Duurzame Infrastructuur voor iedereen",
        "info2" => "Een cruciaal aspect van SDG 9 is de ontwikkeling van duurzame infrastructuur. Dit doel benadrukt dat de ontwikkeling van infrastructuur, zoals wegen, energievoorziening en telecommunicatie, essentieel is voor economische groei en verbetering van de levenskwaliteit. SDG 9 moedigt aan tot investeringen in duurzame infrastructuurprojecten en de bevordering van toegang tot betrouwbare diensten voor iedereen. Door duurzame infrastructuur te ontwikkelen, kunnen we bijdragen aan een wereld waarin niemand wordt buitengesloten van de voordelen van moderne voorzieningen.",
    ],
    [
        "title" => "10: Reduced Inequalities",
        "image" => "/img/sdg10.webp",
        "image2" => "/img/subsdg10.jpg",
        "sub" => "Het Verminderen van Ongelijkheid",
        "info" => "SDG 10 heeft als doel ongelijkheid binnen en tussen landen te verminderen. Het doel streeft naar inclusieve groei en sociale rechtvaardigheid, waarbij de focus ligt op het verminderen van ongelijkheid op basis van inkomen, geslacht, leeftijd, handicap, ras, etniciteit, nationaliteit en andere factoren. SDG 10 benadrukt het belang van inclusiviteit en het creëren van gelijke kansen voor iedereen. Dit doel is gericht op het creëren van een wereld waarin niemand wordt achtergelaten en waarin iedereen kan profiteren van economische vooruitgang.",
        "subtitle2" => "Kansen voor Gemarginaliseerde Groepen",
        "info2" => "Een belangrijk aspect van SDG 10 is het bieden van kansen voor gemarginaliseerde groepen. Dit doel benadrukt de noodzaak om discriminatie en uitsluiting aan te pakken, met speciale aandacht voor mensen in kwetsbare situaties. SDG 10 moedigt aan tot het bevorderen van beleid en maatregelen die gelijkheid en inclusiviteit bevorderen. Door kansen te creëren voor gemarginaliseerde groepen, kunnen we bijdragen aan een wereld waarin iedereen volwaardig deelneemt aan de samenleving en de economische groei.",
    ],
    [
        "title" => "11: Sustainable Cities",
        "image" => "/img/sdg11.webp",
        "image2" => "/img/subsdg11.jpg",
        "sub" => "Duurzame Steden voor Iedereen",
        "info" => "SDG 11 heeft als doel duurzame steden en gemeenschappen te bevorderen. Het doel streeft naar de ontwikkeling van steden die inclusief, veilig, veerkrachtig en duurzaam zijn. SDG 11 benadrukt het belang van verbeterde stedelijke planning en beheer om de levenskwaliteit te verbeteren. Dit doel richt zich op thema's zoals toegankelijkheid, groene ruimtes, en de bescherming van cultureel erfgoed. Het doel is om steden te creëren waarin iedereen kan genieten van een hoge levenskwaliteit.",
        "subtitle2" => "Slimme en Veerkrachtige Steden",
        "info2" => "Een belangrijk aspect van SDG 11 is de bevordering van slimme en veerkrachtige steden. Dit doel benadrukt de noodzaak van innovatieve oplossingen en technologieën om steden duurzaam en efficiënt te maken. SDG 11 moedigt aan tot investeringen in infrastructuur, openbaar vervoer, en milieubescherming binnen steden. Door steden slim en veerkrachtig te maken, kunnen we bijdragen aan een wereld waarin gemeenschappen gedijen, milieubescherming centraal staat, en stedelijke groei in evenwicht is met duurzaamheid.",
    ],
    [
        "title" => "12: Responsible Consumption",
        "image" => "/img/sdg12.webp",
        "image2" => "/img/subsdg12.jpg",
        "sub" => "Duurzame Consumptie en Productie",
        "info" => "SDG 12 streeft naar verantwoorde consumptie en productiepatronen. Het doel is om verspilling te verminderen en de efficiëntie in het gebruik van natuurlijke hulpbronnen te verbeteren. SDG 12 benadrukt het belang van bewuste consumptie, recycling, en de bevordering van duurzame productiepraktijken. Dit doel is gericht op het creëren van een wereld waarin we onze natuurlijke hulpbronnen respecteren en gebruiken op een manier die de planeet en toekomstige generaties beschermt.",
        "subtitle2" => "Bewuste Keuzes voor een Duurzamere Toekomst",
        "info2" => "Een belangrijk aspect van SDG 12 is het aanmoedigen van bewuste keuzes voor een duurzamere toekomst. Dit doel benadrukt dat individuen, bedrijven en overheden verantwoordelijk zijn voor hun consumptie- en productiegedrag. SDG 12 moedigt aan tot het verminderen van afval, het hergebruiken van materialen, en het aannemen van circulaire economiemodellen. Door bewuste keuzes te maken voor een duurzamere toekomst, kunnen we bijdragen aan een wereld waarin de behoeften van het heden worden vervuld zonder de mogelijkheden van toekomstige generaties in gevaar te brengen.",
    ],
    [
        "title" => "13: Climate Action",
        "image" => "/img/sdg13.webp",
        "image2" => "/img/subsdg13.jpg",
        "sub" => "Actie voor het Klimaat",
        "info" => "SDG 13 heeft als doel actie te ondernemen om klimaatverandering aan te pakken en de gevolgen ervan te verminderen. Het doel streeft naar wereldwijde inspanningen om de opwarming van de aarde te beperken en de veerkracht van gemeenschappen tegen klimaatgerelateerde rampen te vergroten. SDG 13 benadrukt het belang van bewustwording en maatregelen om de uitstoot van broeikasgassen te verminderen en duurzame praktijken te bevorderen. Dit doel is gericht op het creëren van een wereld waarin we het klimaat beschermen voor toekomstige generaties.",
        "subtitle2" => "Klimaatadaptatie en Veerkracht",
        "info2" => "Een belangrijk aspect van SDG 13 is het bevorderen van klimaatadaptatie en veerkracht. Dit doel benadrukt dat we ons moeten voorbereiden op de gevolgen van klimaatverandering en gemeenschappen veerkrachtiger moeten maken. SDG 13 moedigt aan tot investeringen in klimaatbestendige infrastructuur, waterbeheer en duurzame landbouwpraktijken. Door klimaatadaptatie en veerkracht te bevorderen, kunnen we bijdragen aan een wereld waarin gemeenschappen beter in staat zijn om zich aan te passen aan veranderende klimaatomstandigheden en zichzelf beschermen tegen klimaatgerelateerde risico's.",
    ],
    [
        "title" => "14: Life Below Water",
        "image" => "/img/sdg14.webp",
        "image2" => "/img/subsdg14.jpg",
        "sub" => "Behoud van Oceaangezondheid",
        "info" => "SDG 14 streeft naar het behoud van oceaangezondheid en het duurzaam beheer van het leven in het water. Het doel richt zich op het beschermen van de oceanen en hun biodiversiteit tegen vervuiling, overbevissing en de vernietiging van leefgebieden. SDG 14 benadrukt het belang van internationale samenwerking om maritieme ecosystemen te behouden en te herstellen. Dit doel is gericht op het creëren van een wereld waarin de oceanen gezond zijn en een cruciale rol spelen in het handhaven van het milieu.",
        "subtitle2" => "Bescherming van Kustgemeenschappen",
        "info2" => "Een belangrijk aspect van SDG 14 is de bescherming van kustgemeenschappen. Dit doel benadrukt de noodzaak om kustgemeenschappen te ondersteunen en hen veerkrachtiger te maken tegen klimaatverandering en zeespiegelstijging. SDG 14 moedigt aan tot maatregelen om mariene hulpbronnen duurzaam te gebruiken en kustgebieden te beschermen tegen rampen. Door de bescherming van kustgemeenschappen te bevorderen, kunnen we bijdragen aan een wereld waarin zowel menselijke gemeenschappen als het leven in de oceanen gedijen.",
    ],
    [
        "title" => "15: Life On Land",
        "image" => "/img/sdg15.webp",
        "image2" => "/img/subsdg15.jpg",
        "sub" => "Behoud van Terrestrische Ecosystemen",
        "info" => "SDG 15 heeft als doel terrestrische ecosystemen te behouden en duurzaam beheren. Het doel streeft naar het stoppen van de degradatie van land- en bosgebieden, en het beschermen van de biodiversiteit op het land. SDG 15 benadrukt het belang van verantwoord bosbeheer, het herstellen van aangetaste ecosystemen en het voorkomen van verdere landdegradatie. Dit doel is gericht op het creëren van een wereld waarin het leven op het land floreert en bijdraagt aan ecologische stabiliteit.",
        "subtitle2" => "Bestrijding van Woestijnvorming",
        "info2" => "Een belangrijk aspect van SDG 15 is de bestrijding van woestijnvorming en bodemdegradatie. Dit doel benadrukt de noodzaak om verwoestijning tegen te gaan en vruchtbare grond te behouden. SDG 15 moedigt aan tot duurzaam landbeheer en bodemherstelmaatregelen om landdegradatie te voorkomen. Door de bestrijding van woestijnvorming te bevorderen, kunnen we bijdragen aan een wereld waarin vruchtbare grond behouden blijft en landbouwpraktijken duurzaam zijn.",
    ],
    [
        "title" => "16: Peace and Justice",
        "image" => "/img/sdg16.webp",
        "image2" => "/img/subsdg16.jpg",
        "sub" => "Bevordering van Vrede en Rechtvaardigheid",
        "info" => "SDG 16 heeft als doel vrede, rechtvaardigheid en sterke publieke diensten te bevorderen. Het doel streeft naar het verminderen van geweld, het voorkomen van conflicten en het bevorderen van vreedzame samenlevingen. SDG 16 benadrukt het belang van toegang tot rechtvaardigheid voor iedereen en het versterken van de publieke diensten. Dit doel is gericht op het creëren van een wereld waarin vrede en rechtvaardigheid de norm zijn en waarin alle burgers kunnen profiteren van sterke en inclusieve instellingen.",
        "subtitle2" => "Voorkomen van Corruptie en Misdaad",
        "info2" => "Een belangrijk aspect van SDG 16 is het voorkomen van corruptie en misdaad. Dit doel benadrukt de noodzaak om corruptie te bestrijden, inclusief omkoping en illegale financiële stromen. SDG 16 moedigt aan tot verantwoordelijke en transparante regeringen en organisaties. Door corruptie en misdaad te voorkomen, kunnen we bijdragen aan een wereld waarin eerlijkheid, integriteit en veiligheid overheersen en waarin publieke diensten efficiënt werken ten behoeve van alle burgers.",
    ],
    [
        "title" => "17: Partnerships for the Gols",
        "image" => "/img/sdg17.webp",
        "image2" => "/img/subsdg17.jpg",
        "sub" => "Mondiaal Samenwerken",
        "info" => "SDG 17 heeft als doel mondiale samenwerking te bevorderen om de doelstellingen van duurzame ontwikkeling te bereiken. Het doel streeft naar het versterken van partnerschappen tussen landen, overheden, bedrijven en maatschappelijke organisaties om gezamenlijk actie te ondernemen. SDG 17 benadrukt het belang van gedeelde verantwoordelijkheid en gedeelde voordelen. Dit doel is gericht op het creëren van een wereld waarin internationale samenwerking de drijvende kracht is achter de realisatie van alle duurzame ontwikkelingsdoelen.",
        "subtitle2" => "Financiële Ondersteuning en Capaciteitsopbouw",
        "info2" => "Een belangrijk aspect van SDG 17 is het bieden van financiële ondersteuning en capaciteitsopbouw aan ontwikkelingslanden. Dit doel benadrukt de noodzaak om ontwikkelingslanden te helpen bij het mobiliseren van financiële middelen en het opbouwen van capaciteit om duurzame ontwikkeling te realiseren. SDG 17 moedigt aan tot investeringen in technologieoverdracht, kennisdeling en handelsfacilitatie. Door financiële ondersteuning en capaciteitsopbouw te bieden, kunnen we bijdragen aan een wereld waarin alle landen gelijke toegang hebben tot de middelen die nodig zijn voor duurzame groei.",
    ],
];